/random_generate:  # RandomPointGenerator节点命名空间
  ros__parameters:
    coordinate_precision: "high" # 可选择生成的随机点精度，与第二个参数一起使用，高精度为小数点后若干位浮点数
    decimal_places: 1  # 低精度会使得生成点的坐标是小数点后x位，x由本参数指定
    map_x: 14.0        # 设定赛场边界，|x|的最大值，可取正取负
    map_y: 7.0       # 设定赛场边界，|y|的最大值，可取正取负，正负值代表正负方向
    center_x: 14.0      # 球筐x坐标
    center_y: 3.5    # 球筐y坐标
    origin_x: 0.0      # 起始点x坐标
    origin_y: 0.0      # 起始点y坐标
    radius_min: 3.0    # 生成随机点最小半径
    radius_max: 4.0    # 生成随机点最大半径
    num_points: 60     # 生成随机点数量
    safety_distance: 0.5  # 与地图边界的生成点安全距离，在传入的赛场范围的内区间范围内不会生成点
    publish_mode: "fixed" # 生成随机点策略，fixed为生成不变固定点，dynamic为生成变化随机点
    continuous_publish: true # 是否持续生成点，建议保留true
    publish_frequency: 2.0  # 点的发布频率（HZ）
    half_circle: true   # 是否只在半圆环生成点，建议保留true
    min_generation_interval: 0.5 # 点生成的最小时间间隔

/optimal_point_selector:  # OptimalPointSelector节点命名空间
  ros__parameters:
    center_x: 14.0  # 篮筐（圆心）x坐标
    center_y: 3.5 # 篮筐（圆心）y坐标
    refer_point_x: 0.0 # 辅助点（篮筐的对长点）x坐标
    refer_point_y: 3.5 # 辅助点（篮筐的对长点）y坐标
    comd_r: 2.5 # 指令半径（最佳投球半径）
    a: 1.0 # 障碍物评分参数
    b: 1.0 # 角度评分参数
    c: 1.0 # 半径匹配评分参数
    d: 1.0 # 机器人距离评分参数
    map_frame: map
    robot_frame: base_link
    dist_decay: 1.5    # 衰减因子，值尽可能小于5,值越大，稍远距离的点得分衰减越快
    max_diff: 3.0 # 半径匹配最大允许半径差值，大于此差值的（实际距圆心距离-com_r最佳半径的点会被截断）

/obstacle_extractor:  # ObstacleExtractor节点命名空间
  ros__parameters:
    costmap_topic: "/local_costmap/costmap"  # 订阅的障碍地图话题
    # 划定障碍点采纳区间
    region_origin_x: 0.0  # 障碍点采纳区间原点x
    region_origin_y: 0.0  # 原点y
    region_xlength: 14.0  # 障碍点采纳区间x长度
    region_ylength: 7.0  # y长度 


/optimal_goal_navigator:  # OptimalGoalNavigator节点命名空间
  ros__parameters:
    is_dynamic: false  # 是否允许导航动态打断，允许最优点变化
    goal_timeout: 30.0 # 导航超时时间
    max_failures: 20   # 导航最大重试次数
    center_x: 14.0  # 篮筐（圆心）x坐标
    center_y: 3.5 # 篮筐（圆心）y坐标
